[config]
skip_core_tasks = true
skip_git_env_info = true

[env]
BOOTLOADER_DIRECTORY = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/loader"
INITRD_DIRECTORY = "${BOOTLOADER_DIRECTORY}/initrd"
OVMF_URL = "https://retrage.github.io/edk2-nightly/bin/RELEASEX64_OVMF.fd"
ARM_QEMU_CODE = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "/usr/share/AAVMF/AAVMF_CODE.fd", mapping = { "macos" = "/opt/homebrew/share/qemu/edk2-aarch64-code.fd" } }
ARM_QEMU_VARS_TEMPLATE = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "/usr/share/AAVMF/AAVMF_VARS.fd", mapping = { "macos" = "/opt/homebrew/share/qemu/edk2-arm-vars.fd" } }
TOWBOOT_DIRECTORY = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/tools/towboot"
TOWBOOTCTL = "${TOWBOOT_DIRECTORY}/target/debug/towbootctl"
TAR = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "tar", mapping = { "macos" = "gtar" } }
LINKER = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "ld", mapping = { "macos" = "x86_64-elf-ld" } }
QEMU_AUDIO_DEVICE = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "pa", mapping = { "macos" = "coreaudio" } }
QEMU_DISPLAY = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "gtk,gl=on", mapping = { "macos" = "cocoa" } }
QEMU_VIRTIO_DEVICE = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "virtio-vga-gl", mapping = { "macos" = "virtio-vga" } }
RUSTFLAGS="--cfg getrandom_backend=\"rdrand\""

#VIRGL_DEBUG = "all"
#GALLIUM_DEBUG = "trace"


[tasks.default]
alias = "qemu"

# Run tasks

[tasks.qemu]
command = "qemu-system-x86_64"
dependencies = [ "image", "hdd", "ovmf" ]
env = { KERNEL_ARCH = "x86_64" }
args = [
    # Base machine configuration
    "-machine", "q35,nvdimm=on,pcspk-audiodev=audio0",
    "-m", "512M,slots=2,maxmem=1G",
    "-cpu", "Haswell,fsgsbase",
    "-smp", "4", # 4 CPUs
    "-bios", "RELEASEX64_OVMF.fd",
    "-boot", "d",
    "-vga", "none",
    "-rtc", "base=localtime",
    "-serial", "stdio",
    #"-trace", "virtio_gpu_*",
    #"-trace", "virtio_gpu_virgl_process_cmd",

    # Hard disk drive configuration
    "-device", "piix3-ide,id=ide",  # IDE Controller
    "-device", "ahci,id=ahci",      # AHCI Controller
    "-drive", "driver=raw,if=none,id=boot,file.filename=d3os.img",  # Boot drive
    "-drive", "driver=raw,if=none,id=hdd,file.filename=hdd.img",    # HDD drive containing root filesystem
    "-device", "ide-hd,bus=ahci.0,drive=boot",  # Attach boot drive to AHCI controller (boots faster than on the IDE controller)
    "-device", "ide-hd,bus=ide.0,drive=hdd",    # Attach HDD drive to IDE controller (D3OS does not support AHCI yet)

    # NVDIMM configuration
    "-device", "nvdimm,memdev=mem1,id=nv1,label-size=2M",
    "-object", "memory-backend-file,id=mem1,share=on,mem-path=nvdimm0,size=16M",

    # Network configuration
    "-nic", "model=rtl8139,id=rtl8139,hostfwd=udp::1797-:1797,hostfwd=tcp::1797-:1797",
    "-object", "filter-dump,id=filter1,netdev=rtl8139,file=rtl8139.dump",

    # VirtIO Devices
    "-display", "${QEMU_DISPLAY}",
    "-device", "${QEMU_VIRTIO_DEVICE}", # virtio-gpu-pci, virtio-vga
    "-device", "virtio-rng-pci",
    #"-device", "virtio-keyboard-pci",
    #"-device", "virtio-mouse-pci",
    #"-device", "vhost-vsock-pci,guest-cid=3",
    #"-device", "virtio-sound-pci,audiodev=audio0",

    # Audio configuration (Using pulse audio for Linux)
    "-audiodev", "id=audio0,driver=${QEMU_AUDIO_DEVICE}",
]

[tasks.qemu-arm]
command = "qemu-system-aarch64"
dependencies = [ "image-arm", "hdd", "aavmf-vars" ]
env = { KERNEL_ARCH = "aarch64" }
args = [
    "-machine", "virt",
    "-cpu", "cortex-a57",
    "-m", "512M",
    "-serial", "stdio",
    "-device", "ramfb",
    "-drive", "if=pflash,format=raw,readonly=on,file=${ARM_QEMU_CODE}",
    "-drive", "if=pflash,format=raw,file=${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/AAVMF_VARS.fd",
    "-drive", "driver=raw,if=none,id=boot,file.filename=d3os-arm.img",
    "-drive", "driver=raw,if=none,id=hdd,file.filename=hdd.img",
    "-device", "virtio-blk-device,drive=boot",
    "-device", "virtio-blk-device,drive=hdd",
]

[tasks.aavmf-vars]
command = "cp"
args = [ "${ARM_QEMU_VARS_TEMPLATE}", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/AAVMF_VARS.fd" ]
condition = { files_not_exist = [ "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/AAVMF_VARS.fd" ] }

[tasks.qemu-wsl]
command = "qemu-system-x86_64.exe"
dependencies = [ "image", "hdd", "ovmf" ]
env = { KERNEL_ARCH = "x86_64", WSL_BIOS_PATH = { script = ["wslpath -w 'RELEASEX64_OVMF.fd'"]}, WSL_BOOT_PATH = { script = ["wslpath -w 'd3os.img'"] }, WSL_HDD_PATH = { script = ["wslpath -w 'hdd.img'"]} }
args = [
    # Base machine configuration
    "-machine", "q35,nvdimm=on,pcspk-audiodev=audio0",
    "-m", "512M,slots=2,maxmem=1G",
    "-cpu", "Haswell",
    "-smp", "4", # 4 CPUs
    "-bios", "${WSL_BIOS_PATH}",
    "-boot", "d",
    "-vga", "std",
    "-rtc", "base=localtime",
    "-serial", "stdio",

    # Hard disk drive configuration
    "-device", "piix3-ide,id=ide",  # IDE Controller
    "-device", "ahci,id=ahci",      # AHCI Controller
    "-drive", "driver=raw,if=none,id=boot,file.filename=${WSL_BOOT_PATH}",  # Boot drive
    "-drive", "driver=raw,if=none,id=hdd,file.filename=${WSL_HDD_PATH}",    # HDD drive containing root filesystem
    "-device", "ide-hd,bus=ahci.0,drive=boot",  # Attach boot drive to AHCI controller (boots faster than on the IDE controller)
    "-device", "ide-hd,bus=ide.0,drive=hdd",    # Attach HDD drive to IDE controller (D3OS does not support AHCI yet)

    # NVDIMM configuration
    #"-device", "nvdimm,memdev=mem1,id=nv1,label-size=2M",
    #"-object", "memory-backend-file,id=mem1,share=on,mem-path=nvdimm0,size=16M",

    # Network configuration
    "-nic", "model=rtl8139,id=rtl8139,hostfwd=udp::1797-:1797",
    "-object", "filter-dump,id=filter1,netdev=rtl8139,file=rtl8139.dump",

    # Audio configuration (Using pulse audio for Linux)
    "-audiodev", "id=audio0,driver=sdl",

    # Windows Hyper-V acceleration
    "-accel", "whpx",
]

[tasks.debug]
command = "qemu-system-x86_64"
dependencies = [ "debug-signal-vscode" ]
env = { KERNEL_ARCH = "x86_64" }
args = [
    # Base machine configuration
    "-machine", "q35,nvdimm=on,pcspk-audiodev=audio0",
    "-m", "512M,slots=2,maxmem=1G",
    "-cpu", "Haswell",
    "-smp", "4", # 4 CPUs
    "-bios", "RELEASEX64_OVMF.fd",
    "-boot", "c",
    "-vga", "none",
    "-rtc", "base=localtime",
    "-serial", "stdio",

    # Hard disk drive configuration
    "-device", "piix3-ide,id=ide",  # IDE Controller
    "-device", "ahci,id=ahci",      # AHCI Controller
    "-drive", "driver=raw,if=none,id=boot,file.filename=d3os.img",  # Boot drive
    "-drive", "driver=raw,if=none,id=hdd,file.filename=hdd.img",    # HDD drive containing root filesystem
    "-device", "ide-hd,bus=ahci.0,drive=boot",  # Attach boot drive to AHCI controller (boots faster than on the IDE controller)
    "-device", "ide-hd,bus=ide.0,drive=hdd",    # Attach HDD drive to IDE controller (D3OS does not support AHCI yet)

    # NVDIMM configuration
    "-device", "nvdimm,memdev=mem1,id=nv1,label-size=2M",
    "-object", "memory-backend-file,id=mem1,share=on,mem-path=nvdimm0,size=16M",

    # Network configuration
    "-nic", "model=rtl8139,id=rtl8139,hostfwd=udp::1797-:1797,hostfwd=tcp::1797-:1797",
    "-object", "filter-dump,id=filter1,netdev=rtl8139,file=rtl8139.dump",

    # VirtIO Devices
    "-display", "${QEMU_DISPLAY},gl=on",
    "-device", "virtio-vga-gl", # virtio-gpu-pci, virtio-vga
    "-device", "virtio-rng-pci",
    #"-device", "virtio-keyboard-pci",
    #"-device", "virtio-mouse-pci",
    #"-device", "vhost-vsock-pci,guest-cid=3",
    #"-device", "virtio-sound-pci,audiodev=audio0",

    # Audio configuration (Using pulse audio for Linux)
    "-audiodev", "id=audio0,driver=${QEMU_AUDIO_DEVICE}",

    # Trace events
    #"-d", "trace:ps2_write_keyboard,trace:ps2_read_data,trace:ps2_mouse_send_packet,trace:ps2_mouse_fake_event,trace:ps2_write_mouse,trace:ps2_mouse_reset",

    # Debugging configuration
    "-S", "-gdb", "tcp::1234"
]

[tasks.debug-signal-vscode]
command = "echo"
args = [ "Ready to debug" ]
dependencies = [ "image", "hdd", "ovmf" ]

[tasks.gdb]
command = "gdb"
args = [ "-ex", "break start", "-ex", "target remote 127.0.0.1:1234", "-ex", "continue", "loader/kernel.elf" ]

[tasks.ovmf]
command = "wget"
args = [ "-N", "${OVMF_URL}" ]

[tasks.test]
command = "cargo"
args = [ "test" ]

# Build tasks

[tasks.link-members]
run_task = { name = "link", fork = true }
dependencies = [ "create-initrd-directory" ]
env = { KERNEL_ARCH = "x86_64" }

[tasks.link-members-arm]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/os/kernel"
command = "cargo"
args = [ "make", "--no-workspace", "link" ]
dependencies = [ "create-initrd-directory" ]
env = { KERNEL_ARCH = "aarch64" }

[tasks.check-members]
run_task = { name = "check", fork = true }

[tasks.clippy-members]
run_task = { name = "clippy", fork = true }

[tasks.create-initrd-directory]
command = "mkdir"
args = [ "-p", "${INITRD_DIRECTORY}", "${INITRD_DIRECTORY}/bin" ]
condition = { files_not_exist = [ "${INITRD_DIRECTORY}/bin" ] }

[tasks.initrd]
cwd = "${INITRD_DIRECTORY}"
command = "${TAR}"
args = [ "-cf", "${BOOTLOADER_DIRECTORY}/initrd.tar", "bin/", "usr/" ]
dependencies = [ "link-members" ]
condition = { files_modified = { input = [ "${INITRD_DIRECTORY}/**/*" ], output = [ "${BOOTLOADER_DIRECTORY}/initrd.tar" ] } }

[tasks.initrd-arm]
cwd = "${INITRD_DIRECTORY}"
command = "${TAR}"
args = [ "-cf", "${BOOTLOADER_DIRECTORY}/initrd.tar", "bin/", "usr/" ]
dependencies = [ "link-members-arm" ]
condition = { files_modified = { input = [ "${INITRD_DIRECTORY}/**/*" ], output = [ "${BOOTLOADER_DIRECTORY}/initrd.tar" ] } }

[tasks.create-hdd-fill-img]
cwd = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}"
command = "fallocate"
args = [ "-l", "1M", "fill.img" ]
condition = { files_not_exist = [ "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/fill.img" ] }

[tasks.create-hdd-fill-img.mac]
command = "mkfile"
args = [ "-n", "1m", "fill.img" ]

[tasks.create-hdd-partition-img]
cwd = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}"
command = "mkfs.vfat"
args = [ "-C", "part.img", "63488" ]
condition = { files_not_exist = [ "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/part.img" ] }

[tasks.hdd]
script = '''
cat ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/fill.img ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/part.img ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/fill.img > "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/hdd.img"
echo -e 'o\nn\np\n1\n2048\n131071\nt\ne\nw\n' | fdisk "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/hdd.img"
'''
dependencies = [ "create-hdd-fill-img", "create-hdd-partition-img" ]
condition = { files_modified = { input = [ "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/fill.img", "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/part.img" ], output = [ "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/hdd.img" ] } }

[tasks.image]
cwd = "${BOOTLOADER_DIRECTORY}"
command = "${TOWBOOTCTL}"
env = { KERNEL_ARCH = "x86_64" }
args = [ "image", "--target", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/d3os.img", "--", "-config", "towboot.toml"]
dependencies = [ "link-members", "initrd", "towbootctl" ]
condition = { files_modified = { input = [ "${BOOTLOADER_DIRECTORY}/initrd.tar", "${BOOTLOADER_DIRECTORY}/kernel.elf", "${BOOTLOADER_DIRECTORY}/towboot.toml", "${TOWBOOTCTL}" ], output = [ "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/d3os.img" ] } }

[tasks.image-arm]
cwd = "${BOOTLOADER_DIRECTORY}"
command = "${TOWBOOTCTL}"
env = { KERNEL_ARCH = "aarch64" }
args = [ "image", "--target", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/d3os-arm.img", "--", "-config", "towboot.toml"]
dependencies = [ "link-members-arm", "initrd-arm", "towbootctl" ]
condition = { files_modified = { input = [ "${BOOTLOADER_DIRECTORY}/initrd.tar", "${BOOTLOADER_DIRECTORY}/kernel.elf", "${BOOTLOADER_DIRECTORY}/towboot.toml", "${TOWBOOTCTL}" ], output = [ "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/d3os-arm.img" ] } }

[tasks.towbootctl]
cwd = "${TOWBOOT_DIRECTORY}"
command = "rustup"
args = [ "run", "nightly", "cargo", "build", "-p", "towbootctl", "--features", "binary" ]
condition = { files_modified = { input = [ "${TOWBOOT_DIRECTORY}/Cargo.toml", "${TOWBOOT_DIRECTORY}/Cargo.lock", "${TOWBOOT_DIRECTORY}/rust-toolchain.toml", "${TOWBOOT_DIRECTORY}/towboot/**/*.rs", "${TOWBOOT_DIRECTORY}/towboot_aa64/**/*.rs", "${TOWBOOT_DIRECTORY}/towboot_aa64/Cargo.toml", "${TOWBOOT_DIRECTORY}/towbootctl/**/*.rs", "${TOWBOOT_DIRECTORY}/towbootctl/Cargo.toml" ], output = [ "${TOWBOOTCTL}" ] } }

# Cleanup tasks

[tasks.clean]
dependencies = [ "clean-workspace", "clean-members" ]

[tasks.clean-workspace]
command = "rm"
args = [ "-rf",
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/d3os.img",
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/d3os-arm.img",
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/hdd.img",
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/AAVMF_VARS.fd",
    "${BOOTLOADER_DIRECTORY}/kernel.elf",
    "${BOOTLOADER_DIRECTORY}/initrd.tar",
    "${INITRD_DIRECTORY}/bin",
    "RELEASEX64_OVMF.fd",
    "towbootctl" ]

[tasks.clean-members]
run_task = { name = "clean", fork = true }
